# This file was generated by GoReleaser. DO NOT EDIT.
cask "repomind" do
  version "2.0.0"

  on_macos do
    on_arm do
      sha256 "d74c684d0a1df82fa527b810c2382889a688aa4b0d2554f86149d2ba24711148"
      url "https://github.com/repomind-dev/repomind/releases/download/v#{version}/repomind_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e9925a8d5fecde21e3ca5eb79aae7464403dfecc7e257010f7d944fe3c2c4c34"
      url "https://github.com/repomind-dev/repomind/releases/download/v#{version}/repomind_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "836ccbb7a540b8a9a3fa00d8becbd9d8a3ce573785d13971171f6b389c7dab8d"
      url "https://github.com/repomind-dev/repomind/releases/download/v#{version}/repomind_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "ebfad18b01d986153f2ef27e192b2b8069c72fbef4ef297f8a96e51b20cd36c7"
      url "https://github.com/repomind-dev/repomind/releases/download/v#{version}/repomind_#{version}_linux_amd64.tar.gz"
    end
  end

  name "repomind"
  desc "AI-powered git commit messages and repository insights"
  homepage "https://repomind.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "repomind"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"], print_stderr: false).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/repomind"]
    end
  end

  # No zap stanza required
end
