# This file was generated by GoReleaser. DO NOT EDIT.
cask "repomind" do
  version "2.0.0"

  on_macos do
    on_arm do
      sha256 "5fec5337f53080643b65503f20a751b550d2d4a13c0d36ff0b7b6baedd6cd47f"
      url "https://github.com/repomind-dev/repomind/releases/download/v#{version}/repomind_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "fcdb7c49510e63995d931e871582bedc6701b6b9856151ee93de65b11e85f275"
      url "https://github.com/repomind-dev/repomind/releases/download/v#{version}/repomind_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "5b99dd155d1365cbebd6525f963c144d378fb1e8640284bf1ecced781ea12dba"
      url "https://github.com/repomind-dev/repomind/releases/download/v#{version}/repomind_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "2da40b54d0bd57a769e2ecdeab913e888153135223697d9ef0fd0959da86f67b"
      url "https://github.com/repomind-dev/repomind/releases/download/v#{version}/repomind_#{version}_linux_amd64.tar.gz"
    end
  end

  name "repomind"
  desc "AI-powered git commit messages and repository insights"
  homepage "https://repomind.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "repomind"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"], print_stderr: false).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/repomind"]
    end
  end

  # No zap stanza required
end
