# This file was generated by GoReleaser. DO NOT EDIT.
cask "repomind" do
  version "2.0.0"

  on_macos do
    on_arm do
      sha256 "01db834248adcaf0680dab7f0a1a9e14ef2e59293b4f3078e866a0af2a53e02f"
      url "https://github.com/repomind-dev/repomind/releases/download/v#{version}/repomind_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "8e4dd59cd20ccb54a42f16ab936986f5150eeee75feebfa09b16045576d41b54"
      url "https://github.com/repomind-dev/repomind/releases/download/v#{version}/repomind_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "250a47453a22bff76fb072d7573ab1a6f41b67e02b7055540db1d6575cb2c776"
      url "https://github.com/repomind-dev/repomind/releases/download/v#{version}/repomind_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "0f5575a795b2c1e30ef20607a3eca124ade38d52bedf0a23b3bb19c1029a6e5d"
      url "https://github.com/repomind-dev/repomind/releases/download/v#{version}/repomind_#{version}_linux_amd64.tar.gz"
    end
  end

  name "repomind"
  desc "AI-powered git commit messages and repository insights"
  homepage "https://repomind.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "repomind"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"], print_stderr: false).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/repomind"]
    end
  end

  # No zap stanza required
end
